version: '3'

services:
  e-learning-api-app:
    build:
      context: .  # مسار Dockerfile
      target: development
    container_name: e-learning-api
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
    depends_on:
      - db
      - adminer
    volumes:
      - ./src:/app/src:ro
    command: npm run start:dev
    restart: always

  db:
    image: mysql:5.7
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    restart: always
    ports:
      - '8886:3306'
    volumes:
      - dbdata:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8090:8080'

volumes:
  dbdata:

